name: lingo_learn
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # localization
  easy_localization: ^3.0.2

  # DI
  get_it: ^7.6.0
  injectable: ^2.1.2

  # Modeling
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1

  # State management
  equatable: ^2.0.3
  flutter_bloc: ^8.1.2

  # dev
  dartz: ^0.10.1
  intl: ^0.19.0
  tuple: ^2.0.1
  logger: ^2.3.0

  #client
  dio: ^5.3.0
  #ui
  flutter_screenutil: ^5.7.0
  shared_preferences: ^2.1.0
  flutter_svg: ^2.0.10+1
  auto_size_text: ^3.0.0
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  text_scroll: ^0.2.0
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^11.0.0
  form_field_validator: ^1.1.0
  fancy_shimmer_image: ^2.0.2
  dotted_border: ^2.1.0
  easy_stepper: ^0.8.1
  photo_view: ^0.15.0
  loading_animation_widget: ^1.2.0+4
  persistent_bottom_nav_bar: ^6.2.1
  flutter_glow: ^0.3.0
  avatar_glow: ^3.0.1
  fluttertoast: ^8.2.5
  image_picker: ^1.1.1
  path_provider: ^2.1.3
  uuid: ^4.4.0
  flutter_image_compress: ^2.3.0
  shimmer: ^3.0.0
  flutter_pdfview: ^1.3.2
  syncfusion_flutter_pdfviewer: ^26.2.5
  http: ^1.2.2
  flutter_cached_pdfview: ^0.4.2
  video_player: ^2.9.1
  flick_video_player: ^0.8.0
  bloc_concurrency: ^0.2.5
  webview_flutter: ^4.8.0
  firebase_core: ^3.3.0
  printing: ^5.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  bloc_test: ^9.1.1
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  share_plus: ^9.0.0
  carousel_slider: ^4.2.1

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
